"""first migrate

Revision ID: 095b8b91615d
Revises: 
Create Date: 2022-07-06 12:11:46.766570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095b8b91615d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('from_last_name', sa.String(length=200), nullable=True))
    op.add_column('report', sa.Column('from_first_name', sa.String(length=200), nullable=True))
    op.add_column('report', sa.Column('from_role', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'from_role')
    op.drop_column('report', 'from_first_name')
    op.drop_column('report', 'from_last_name')
    # ### end Alembic commands ###
