"""second mi

Revision ID: 1be271a84f57
Revises: 84f8f6b09eb0
Create Date: 2022-07-07 12:56:56.118547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be271a84f57'
down_revision = '84f8f6b09eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addurl', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('sender_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'sender_id')
    op.drop_column('addurl', 'sender_id')
    # ### end Alembic commands ###
