"""565

Revision ID: 302fa1b561e4
Revises: cd13105272cc
Create Date: 2022-07-22 10:41:29.398373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302fa1b561e4'
down_revision = 'cd13105272cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destroyed_token', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_destroyed_token_token'), ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destroyed_token', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_destroyed_token_token'), type_='unique')

    # ### end Alembic commands ###
