"""third m

Revision ID: 83411192556b
Revises: 1be271a84f57
Create Date: 2022-07-08 10:01:02.194819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83411192556b'
down_revision = '1be271a84f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_sign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orders_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_order_sign_orders_id_order'), 'order', ['orders_id'], ['id'])

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_sections_section'), ['section'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_sections_section'), type_='unique')

    with op.batch_alter_table('order_sign', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_sign_orders_id_order'), type_='foreignkey')
        batch_op.drop_column('orders_id')

    # ### end Alembic commands ###
