"""second m

Revision ID: 84f8f6b09eb0
Revises: 095b8b91615d
Create Date: 2022-07-07 09:55:23.736101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f8f6b09eb0'
down_revision = '095b8b91615d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('from_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'from_id')
    # ### end Alembic commands ###
