"""fourth m

Revision ID: ac9c61baa3ff
Revises: 83411192556b
Create Date: 2022-07-09 09:23:34.437864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9c61baa3ff'
down_revision = '83411192556b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:

        batch_op.drop_column('order_id')
        batch_op.drop_column('content')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_report_order_id_order'), 'order', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_report_order_id_order'), type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'report', ['order_id'], ['id'])

    # ### end Alembic commands ###
