"""5333

Revision ID: aff685dc07da
Revises: 302fa1b561e4
Create Date: 2022-07-22 12:25:48.148747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aff685dc07da'
down_revision = '302fa1b561e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_user_tasks')
    op.drop_table('done_user_tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('done_user_tasks',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name='fk_done_user_tasks_report_id_report'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_done_user_tasks_user_id_user')
    )
    op.create_table('all_user_tasks',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name='fk_all_user_tasks_report_id_report'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_all_user_tasks_user_id_user')
    )
    # ### end Alembic commands ###
