"""6664

Revision ID: cd13105272cc
Revises: 210fe39f6944
Create Date: 2022-07-20 17:33:44.457492

"""
from alembic import op
import sqlalchemy as sa
import report


# revision identifiers, used by Alembic.
revision = 'cd13105272cc'
down_revision = '210fe39f6944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phones', report.models.JsonEcodeDict(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('phones')

    # ### end Alembic commands ###
